In [1]:
my_list = [5,2,4,1,7]
my_list

[5, 2, 4, 1, 7]

In [2]:
my_list.append(8)

In [3]:
my_list

[5, 2, 4, 1, 7, 8]

In [4]:
my_list.extend([4,7,1,8])
my_list

[5, 2, 4, 1, 7, 8, 4, 7, 1, 8]

In [5]:
my_list.clear()

In [6]:
my_list

[]

In [7]:
my_list = [5,2,4,1,7]
my_list

[5, 2, 4, 1, 7]

In [8]:
my_list.pop()
my_list

[5, 2, 4, 1]

In [9]:
my_list.remove(2)

In [10]:
my_list

[5, 4, 1]

In [11]:
new_list=my_list.copy()

In [12]:
new_list

[5, 4, 1]

In [13]:
import numpy as np #Object creation for NumPy

In [14]:
#Converting a list into an array
v = np.array(my_list)

In [15]:
v

array([5, 4, 1])

In [16]:
print(v)

[5 4 1]


In [17]:
v = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
v.shape

(3, 3)

In [20]:
v1 = np.array([[5,2,1],[3,7,2],[9,6,4]])

In [21]:
v1

array([[5, 2, 1],
       [3, 7, 2],
       [9, 6, 4]])

In [22]:
v1.shape

(3, 3)

In [23]:
mul= np.matmul(v,v1)

In [24]:
mul

array([[ 38,  34,  17],
       [ 89,  79,  38],
       [140, 124,  59]])

In [25]:
div = np.divide(v,v1)
div

array([[0.2       , 1.        , 3.        ],
       [1.33333333, 0.71428571, 3.        ],
       [0.77777778, 1.33333333, 2.25      ]])

In [26]:
print(v+v1)

[[ 6  4  4]
 [ 7 12  8]
 [16 14 13]]


In [27]:
print(v/v1)

[[0.2        1.         3.        ]
 [1.33333333 0.71428571 3.        ]
 [0.77777778 1.33333333 2.25      ]]


In [28]:
print(v-v1)

[[-4  0  2]
 [ 1 -2  4]
 [-2  2  5]]


In [29]:
#Scientific - Stats, Maths, etc
print(np.mean(v))
print(np.std(v))

5.0
2.581988897471611


In [30]:
#5x5 matrix randomly generate
v2= np.random.randn(5,5)
v2

array([[ 0.15916139,  0.72439232, -0.1676257 , -0.15639774,  0.53523499],
       [-0.35089171,  0.9442049 ,  0.28227631, -0.89814794,  1.51314349],
       [ 0.54079369,  1.00560882, -0.62216996, -0.05342551,  1.31184928],
       [ 1.76430963,  1.33234151, -1.52755432,  0.13992721,  1.25426688],
       [ 1.12148725,  1.66057702, -0.0357136 ,  0.68803625, -0.402321  ]])

In [31]:
v1.T#Transpose of a matrix

array([[5, 3, 9],
       [2, 7, 6],
       [1, 2, 4]])

In [32]:
v1

array([[5, 2, 1],
       [3, 7, 2],
       [9, 6, 4]])

In [33]:
v3 = np.arange(2,11,2)
v3

array([ 2,  4,  6,  8, 10])

In [34]:
a = list(range(2,11,2))
a

[2, 4, 6, 8, 10]

In [35]:
lin = np.linspace(0,3,9)
lin

array([0.   , 0.375, 0.75 , 1.125, 1.5  , 1.875, 2.25 , 2.625, 3.   ])

In [36]:
import pandas as pd #Object creation for Pandas

In [37]:
my_list

[5, 4, 1]

In [38]:
#Converting list into a Series
series = pd.Series(data= my_list)

In [39]:
series

0    5
1    4
2    1
dtype: int64

In [40]:
new_list=[7,4,1,5,2]
series1= pd.Series(data= new_list)

In [41]:
series1

0    7
1    4
2    1
3    5
4    2
dtype: int64

In [42]:
print(series1[3])

5


In [43]:
index_labels = ['zero','first','second', 'third', 'fourth']

In [44]:
series2=pd.Series(data=new_list, index = ['zero','first','second', 'third', 'fourth'])

In [45]:
series2

zero      7
first     4
second    1
third     5
fourth    2
dtype: int64

In [46]:
series2=pd.Series(new_list, index_labels)

In [47]:
series2

zero      7
first     4
second    1
third     5
fourth    2
dtype: int64

In [57]:
#DataFrame creation using the random function of NumPy
df = pd.DataFrame(np.random.randn(5,5),index = index_labels, columns=column_labels)

In [58]:
df

zero_col  first_col  second_col  third_col  fourth_col
zero_row    0.339989   0.724326    0.784867  -2.011205    0.125132
first_row  -0.302197   0.647382    0.503287  -2.085283   -0.901733
second_row -0.203483  -0.255868    1.014194  -1.433269   -0.273126
third_row  -0.499255   2.309005    0.163058   0.097779   -0.841811
fourth_row -0.320198   0.580149   -0.357836  -1.858995    1.457878

In [51]:
index_labels = ['zero_row', 'first_row', 'second_row','third_row','fourth_row']

In [56]:
column_labels = ['zero_col', 'first_col','second_col','third_col','fourth_col']

In [63]:
#Accessing of columns
df[['zero_col']]

zero_col
zero_row    0.339989
first_row  -0.302197
second_row -0.203483
third_row  -0.499255
fourth_row -0.320198

In [64]:
#Acessing of multiple columns
df[['zero_col','third_col']]

zero_col  third_col
zero_row    0.339989  -2.011205
first_row  -0.302197  -2.085283
second_row -0.203483  -1.433269
third_row  -0.499255   0.097779
fourth_row -0.320198  -1.858995

In [71]:
#Accesing of rows using the .loc function
df.loc[['first_row']]

zero_col  first_col  second_col  third_col  fourth_col
first_row -0.302197   0.647382    0.503287  -2.085283   -0.901733

In [70]:
df.loc[['first_row', 'fourth_row']]

zero_col  first_col  second_col  third_col  fourth_col
first_row  -0.302197   0.647382    0.503287  -2.085283   -0.901733
fourth_row -0.320198   0.580149   -0.357836  -1.858995    1.457878

In [75]:
#Accessing of rows through index using the .iloc function
df.iloc[[3]]

zero_col  first_col  second_col  third_col  fourth_col
third_row -0.499255   2.309005    0.163058   0.097779   -0.841811

In [79]:
df.iloc[[3,4]]

zero_col  first_col  second_col  third_col  fourth_col
third_row  -0.499255   2.309005    0.163058   0.097779   -0.841811
fourth_row -0.320198   0.580149   -0.357836  -1.858995    1.457878

In [82]:
df1 = pd.DataFrame({"CustomerID":['101','102','103','104'], "Category":['Cat1','Cat2','Cat3','Cat4'], "Important":['yes','no','yes','yes'], "Sales":[123,152,120,214]},index=[1,2,3,4])

In [83]:
df1

CustomerID Category Important  Sales
1        101     Cat1       yes    123
2        102     Cat2        no    152
3        103     Cat3       yes    120
4        104     Cat4       yes    214

In [84]:
df2 = pd.DataFrame({"CustomerID":['101','102','103','104'], "Color":['Yellow','Orange','Pink','Blue'], "Distance":[12,9,34,35], "Sales":[123,345,220,224]},index=[5,6,7,8])

In [85]:
df2

CustomerID   Color  Distance  Sales
5        101  Yellow        12    123
6        102  Orange         9    345
7        103    Pink        34    220
8        104    Blue        35    224

# Concatenate Function

In [94]:
concatenate = pd.concat([df1,df2],axis=0, sort=False)#axis=0 denotes operations to be carried out from rows

In [95]:
concatenate

CustomerID Category Important  Sales   Color  Distance
1        101     Cat1       yes    123     NaN       NaN
2        102     Cat2        no    152     NaN       NaN
3        103     Cat3       yes    120     NaN       NaN
4        104     Cat4       yes    214     NaN       NaN
5        101      NaN       NaN    123  Yellow      12.0
6        102      NaN       NaN    345  Orange       9.0
7        103      NaN       NaN    220    Pink      34.0
8        104      NaN       NaN    224    Blue      35.0

In [92]:
concatenate1 = pd.concat([df1,df2],axis=1, sort=False)#axis=1 denotes operations to be carried out from columns

In [93]:
concatenate1

CustomerID Category Important  Sales CustomerID   Color  Distance  Sales
1        101     Cat1       yes  123.0        NaN     NaN       NaN    NaN
2        102     Cat2        no  152.0        NaN     NaN       NaN    NaN
3        103     Cat3       yes  120.0        NaN     NaN       NaN    NaN
4        104     Cat4       yes  214.0        NaN     NaN       NaN    NaN
5        NaN      NaN       NaN    NaN        101  Yellow      12.0  123.0
6        NaN      NaN       NaN    NaN        102  Orange       9.0  345.0
7        NaN      NaN       NaN    NaN        103    Pink      34.0  220.0
8        NaN      NaN       NaN    NaN        104    Blue      35.0  224.0

In [97]:
#Using the merge function
merge = pd.merge(df1,df2, how='outer', on='CustomerID')

In [98]:
merge

CustomerID Category Important  Sales_x   Color  Distance  Sales_y
0        101     Cat1       yes      123  Yellow        12      123
1        102     Cat2        no      152  Orange         9      345
2        103     Cat3       yes      120    Pink        34      220
3        104     Cat4       yes      214    Blue        35      224

In [103]:
merge1 = pd.merge(df1,df2, how='inner', on='Sales')

In [104]:
merge1

CustomerID Category Important  Sales_x   Color  Distance  Sales_y
0        101     Cat1       yes      123  Yellow        12      123
1        102     Cat2        no      152  Orange         9      345
2        103     Cat3       yes      120    Pink        34      220
3        104     Cat4       yes      214    Blue        35      224

In [105]:
df

zero_col  first_col  second_col  third_col  fourth_col
zero_row    0.339989   0.724326    0.784867  -2.011205    0.125132
first_row  -0.302197   0.647382    0.503287  -2.085283   -0.901733
second_row -0.203483  -0.255868    1.014194  -1.433269   -0.273126
third_row  -0.499255   2.309005    0.163058   0.097779   -0.841811
fourth_row -0.320198   0.580149   -0.357836  -1.858995    1.457878

In [108]:
df.drop('fourth_col', axis=1, inplace= True)

In [109]:
df

zero_col  first_col  second_col  third_col
zero_row    0.339989   0.724326    0.784867  -2.011205
first_row  -0.302197   0.647382    0.503287  -2.085283
second_row -0.203483  -0.255868    1.014194  -1.433269
third_row  -0.499255   2.309005    0.163058   0.097779
fourth_row -0.320198   0.580149   -0.357836  -1.858995

In [110]:
df.drop('fourth_row', axis=0, inplace=True)

In [111]:
df

zero_col  first_col  second_col  third_col
zero_row    0.339989   0.724326    0.784867  -2.011205
first_row  -0.302197   0.647382    0.503287  -2.085283
second_row -0.203483  -0.255868    1.014194  -1.433269
third_row  -0.499255   2.309005    0.163058   0.097779

In [136]:
df5 = pd.DataFrame({"Q1":[201,203,100], "Q2":[100,101,102]})

In [137]:
df5

Q1   Q2
0  201  100
1  203  101
2  100  102

In [138]:
df6 = pd.DataFrame({"Q3":[220,223,200], "Q4":[300,301,302]})

In [139]:
df6

Q3   Q4
0  220  300
1  223  301
2  200  302

In [140]:
df6.join(df5,how='right')

Q3   Q4   Q1   Q2
0  220  300  201  100
1  223  301  203  101
2  200  302  100  102